[
  {
    "maskCode": "public class Test implements <mask><mask><mask>.EntryPoint {",
    "Glob_context": "//ID = 2389999 public class gwt_class_28 { /** * Entry point classes define <code>onModuleLoad()</code>. */ public class Test implements <mask><mask><mask>.EntryPoint { /** * The message displayed to the user when the server cannot be reached or * returns an error. */ private static final String SERVER_URL = String; private static final String SERVER_ERROR = String + String + String; /** * This is the entry point method. */ public void onModuleLoad() { com.google.gwt.http.client.RequestBuilder requestBuilder = new com.google.gwt.http.client.RequestBuilder(com.google.gwt.http.client.RequestBuilder.GET, SERVER_URL);"
  },
  {
    "maskCode": "<mask><mask><mask>.RequestBuilder requestBuilder = new RequestBuilder(RequestBuilder.GET, SERVER_URL);",
    "Glob_context": "//ID = 2389999 public class gwt_class_28 { /** * Entry point classes define <code>onModuleLoad()</code>. */ public class Test implements com.google.gwt.core.client.EntryPoint { /** * The message displayed to the user when the server cannot be reached or * returns an error. */ private static final String SERVER_URL = String; private static final String SERVER_ERROR = String + String + String; /** * This is the entry point method. */ public void onModuleLoad() { <mask><mask><mask>.RequestBuilder requestBuilder = new com.google.gwt.http.client.RequestBuilder(com.google.gwt.http.client.RequestBuilder.GET, SERVER_URL); try { requestBuilder.sendRequest(null, new Jazz10RequestCallback()); } catch (com.google.gwt.http.client.RequestException e) { com.google.gwt.user.client.Window.alert(String + e.getMessage());"
  },
  {
    "maskCode": "RequestBuilder requestBuilder = new <mask><mask><mask>.RequestBuilder(RequestBuilder.GET, SERVER_URL);",
    "Glob_context": "//ID = 2389999 public class gwt_class_28 { /** * Entry point classes define <code>onModuleLoad()</code>. */ public class Test implements com.google.gwt.core.client.EntryPoint { /** * The message displayed to the user when the server cannot be reached or * returns an error. */ private static final String SERVER_URL = String; private static final String SERVER_ERROR = String + String + String; /** * This is the entry point method. */ public void onModuleLoad() { com.google.gwt.http.client.RequestBuilder requestBuilder = new <mask><mask><mask>.RequestBuilder(com.google.gwt.http.client.RequestBuilder.GET, SERVER_URL); try { requestBuilder.sendRequest(null, new Jazz10RequestCallback()); } catch (com.google.gwt.http.client.RequestException e) { com.google.gwt.user.client.Window.alert(String + e.getMessage());"
  },
  {
    "maskCode": "RequestBuilder requestBuilder = new RequestBuilder(<mask><mask><mask>.RequestBuilder.GET, SERVER_URL);",
    "Glob_context": "//ID = 2389999 public class gwt_class_28 { /** * Entry point classes define <code>onModuleLoad()</code>. */ public class Test implements com.google.gwt.core.client.EntryPoint { /** * The message displayed to the user when the server cannot be reached or * returns an error. */ private static final String SERVER_URL = String; private static final String SERVER_ERROR = String + String + String; /** * This is the entry point method. */ public void onModuleLoad() { com.google.gwt.http.client.RequestBuilder requestBuilder = new com.google.gwt.http.client.RequestBuilder(<mask><mask><mask>.RequestBuilder.GET, SERVER_URL); try { requestBuilder.sendRequest(null, new Jazz10RequestCallback()); } catch (com.google.gwt.http.client.RequestException e) { com.google.gwt.user.client.Window.alert(String + e.getMessage());"
  },
  {
    "maskCode": "} catch (<mask><mask><mask>.RequestException e) {",
    "Glob_context": "/** * This is the entry point method. */ public void onModuleLoad() { com.google.gwt.http.client.RequestBuilder requestBuilder = new com.google.gwt.http.client.RequestBuilder(com.google.gwt.http.client.RequestBuilder.GET, SERVER_URL); try { requestBuilder.sendRequest(null, new Jazz10RequestCallback()); } catch (<mask><mask><mask>.RequestException e) { com.google.gwt.user.client.Window.alert(String + e.getMessage()); } } class Jazz10RequestCallback implements com.google.gwt.http.client.RequestCallback{ public void onError(com.google.gwt.http.client.Request request, Throwable exception) { // never reach here com.google.gwt.user.client.Window.alert(String + exception.getMessage()); } public void onResponseReceived(com.google.gwt.http.client.Request request, com.google.gwt.http.client.Response response) { // render output com.google.gwt.user.client.Window.alert(response.getText());"
  },
  {
    "maskCode": "<mask><mask><mask>.Window.alert(String",
    "Glob_context": "/** * This is the entry point method. */ public void onModuleLoad() { com.google.gwt.http.client.RequestBuilder requestBuilder = new com.google.gwt.http.client.RequestBuilder(com.google.gwt.http.client.RequestBuilder.GET, SERVER_URL); try { requestBuilder.sendRequest(null, new Jazz10RequestCallback()); } catch (com.google.gwt.http.client.RequestException e) { <mask><mask><mask>.Window.alert(String + e.getMessage()); } } class Jazz10RequestCallback implements com.google.gwt.http.client.RequestCallback{ public void onError(com.google.gwt.http.client.Request request, Throwable exception) { // never reach here com.google.gwt.user.client.Window.alert(String + exception.getMessage()); } public void onResponseReceived(com.google.gwt.http.client.Request request, com.google.gwt.http.client.Response response) { // render output com.google.gwt.user.client.Window.alert(response.getText());"
  },
  {
    "maskCode": "class Jazz10RequestCallback implements <mask><mask><mask>.RequestCallback{",
    "Glob_context": "try { requestBuilder.sendRequest(null, new Jazz10RequestCallback()); } catch (com.google.gwt.http.client.RequestException e) { com.google.gwt.user.client.Window.alert(String + e.getMessage()); } } class Jazz10RequestCallback implements <mask><mask><mask>.RequestCallback{ public void onError(com.google.gwt.http.client.Request request, Throwable exception) { // never reach here com.google.gwt.user.client.Window.alert(String + exception.getMessage()); } public void onResponseReceived(com.google.gwt.http.client.Request request, com.google.gwt.http.client.Response response) { // render output com.google.gwt.user.client.Window.alert(response.getText()); } } } };"
  },
  {
    "maskCode": "public void onError(<mask><mask><mask>.Request request, Throwable exception) {",
    "Glob_context": "try { requestBuilder.sendRequest(null, new Jazz10RequestCallback()); } catch (com.google.gwt.http.client.RequestException e) { com.google.gwt.user.client.Window.alert(String + e.getMessage()); } } class Jazz10RequestCallback implements com.google.gwt.http.client.RequestCallback{ public void onError(<mask><mask><mask>.Request request, Throwable exception) { // never reach here com.google.gwt.user.client.Window.alert(String + exception.getMessage()); } public void onResponseReceived(com.google.gwt.http.client.Request request, com.google.gwt.http.client.Response response) { // render output com.google.gwt.user.client.Window.alert(response.getText()); } } } };"
  },
  {
    "maskCode": "<mask><mask><mask>.Window.alert(String",
    "Glob_context": "/** * This is the entry point method. */ public void onModuleLoad() { com.google.gwt.http.client.RequestBuilder requestBuilder = new com.google.gwt.http.client.RequestBuilder(com.google.gwt.http.client.RequestBuilder.GET, SERVER_URL); try { requestBuilder.sendRequest(null, new Jazz10RequestCallback()); } catch (com.google.gwt.http.client.RequestException e) { <mask><mask><mask>.Window.alert(String + e.getMessage()); } } class Jazz10RequestCallback implements com.google.gwt.http.client.RequestCallback{ public void onError(com.google.gwt.http.client.Request request, Throwable exception) { // never reach here com.google.gwt.user.client.Window.alert(String + exception.getMessage()); } public void onResponseReceived(com.google.gwt.http.client.Request request, com.google.gwt.http.client.Response response) { // render output com.google.gwt.user.client.Window.alert(response.getText());"
  },
  {
    "maskCode": "public void onResponseReceived(<mask><mask><mask>.Request request, Response response) {",
    "Glob_context": "} catch (com.google.gwt.http.client.RequestException e) { com.google.gwt.user.client.Window.alert(String + e.getMessage()); } } class Jazz10RequestCallback implements com.google.gwt.http.client.RequestCallback{ public void onError(com.google.gwt.http.client.Request request, Throwable exception) { // never reach here com.google.gwt.user.client.Window.alert(String + exception.getMessage()); } public void onResponseReceived(<mask><mask><mask>.Request request, com.google.gwt.http.client.Response response) { // render output com.google.gwt.user.client.Window.alert(response.getText()); } } } };"
  },
  {
    "maskCode": "public void onResponseReceived(Request request, <mask><mask><mask>.Response response) {",
    "Glob_context": "} catch (com.google.gwt.http.client.RequestException e) { com.google.gwt.user.client.Window.alert(String + e.getMessage()); } } class Jazz10RequestCallback implements com.google.gwt.http.client.RequestCallback{ public void onError(com.google.gwt.http.client.Request request, Throwable exception) { // never reach here com.google.gwt.user.client.Window.alert(String + exception.getMessage()); } public void onResponseReceived(com.google.gwt.http.client.Request request, <mask><mask><mask>.Response response) { // render output com.google.gwt.user.client.Window.alert(response.getText()); } } } };"
  },
  {
    "maskCode": "<mask><mask><mask>.Window.alert(response.getText());",
    "Glob_context": "} catch (com.google.gwt.http.client.RequestException e) { com.google.gwt.user.client.Window.alert(String + e.getMessage()); } } class Jazz10RequestCallback implements com.google.gwt.http.client.RequestCallback{ public void onError(com.google.gwt.http.client.Request request, Throwable exception) { // never reach here com.google.gwt.user.client.Window.alert(String + exception.getMessage()); } public void onResponseReceived(com.google.gwt.http.client.Request request, com.google.gwt.http.client.Response response) { // render output <mask><mask><mask>.Window.alert(response.getText()); } } } };"
  }
]